// AUTO-GENERATED by scripts/sync-question-imports.ts — do not edit manually
import type { ContentQuestion } from "@/lib/content/types";
import { findTopicById } from "@/lib/syllabus/loader";
import type { Question } from "@/lib/types";

import q0 from "../../../content/questions/a-ei-01.json";
import q1 from "../../../content/questions/algebra-batch.json";
import q2 from "../../../content/questions/algebra-ext.json";
import q3 from "../../../content/questions/algebra-fill.json";
import q4 from "../../../content/questions/g-pt-01.json";
import q5 from "../../../content/questions/geometry-ext.json";
import q6 from "../../../content/questions/geometry-fill.json";
import q7 from "../../../content/questions/n-fdp-01.json";
import q8 from "../../../content/questions/n-sc-01.json";
import q9 from "../../../content/questions/number-batch.json";
import q10 from "../../../content/questions/number-ext.json";
import q11 from "../../../content/questions/number-fill.json";
import q12 from "../../../content/questions/p-se-01.json";
import q13 from "../../../content/questions/probability-statistics-batch.json";
import q14 from "../../../content/questions/probability-statistics-ext.json";
import q15 from "../../../content/questions/probability-statistics-fill.json";
import q16 from "../../../content/questions/ratio-ext.json";
import q17 from "../../../content/questions/ratio-fill.json";
import q18 from "../../../content/questions/ratio-geometry-batch.json";

const ALL_CONTENT: ContentQuestion[] = [
  ...(q0 as ContentQuestion[]),
  ...(q1 as ContentQuestion[]),
  ...(q2 as ContentQuestion[]),
  ...(q3 as ContentQuestion[]),
  ...(q4 as ContentQuestion[]),
  ...(q5 as ContentQuestion[]),
  ...(q6 as ContentQuestion[]),
  ...(q7 as ContentQuestion[]),
  ...(q8 as ContentQuestion[]),
  ...(q9 as ContentQuestion[]),
  ...(q10 as ContentQuestion[]),
  ...(q11 as ContentQuestion[]),
  ...(q12 as ContentQuestion[]),
  ...(q13 as ContentQuestion[]),
  ...(q14 as ContentQuestion[]),
  ...(q15 as ContentQuestion[]),
  ...(q16 as ContentQuestion[]),
  ...(q17 as ContentQuestion[]),
  ...(q18 as ContentQuestion[]),
];

export function getAllContentQuestions(): ContentQuestion[] {
  return ALL_CONTENT.filter((q) => q.status === "published");
}

export function getContentQuestionById(id: string): ContentQuestion | undefined {
  return ALL_CONTENT.find((q) => q.id === id);
}

export function getContentQuestionsForTopic(topicId: string): ContentQuestion[] {
  const topic = findTopicById(topicId);
  if (!topic) return [];
  const objectiveIds = new Set(topic.learningObjectives.map((lo) => lo.id));
  return getAllContentQuestions().filter((q) => objectiveIds.has(q.objectiveId));
}

export function toPracticeQuestion(q: ContentQuestion): Question {
  return {
    id: q.id,
    objective_id: q.objectiveId,
    status: "published",
    tier: q.tier,
    difficulty: q.difficulty,
    question_type: q.questionType,
    marks: q.marks,
    exam_style: q.examStyle,
    calculator_allowed: q.calculatorAllowed,
    question_text: q.questionText,
    final_answer: q.finalAnswer,
    solution_steps: q.solutionSteps,
    common_mistakes: "",
    tags: [],
  };
}

export function getPracticeQuestions(topicId?: string | null): Question[] {
  const pool = topicId
    ? getContentQuestionsForTopic(topicId)
    : getAllContentQuestions();
  return pool.map(toPracticeQuestion);
}

export function getQuestionCountByObjective(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const q of getAllContentQuestions()) {
    counts[q.objectiveId] = (counts[q.objectiveId] ?? 0) + 1;
  }
  return counts;
}
