#!/usr/bin/env npx tsx
/**
 * Regenerates src/lib/content/questions.ts imports from all JSON files in content/questions/.
 */
import { readdirSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dirname, "..");
const QUESTIONS_DIR = join(ROOT, "content/questions");
const OUT = join(ROOT, "src/lib/content/questions.ts");

const files = readdirSync(QUESTIONS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

const imports = files
  .map((f, i) => {
    const varName = `q${i}`;
    return `import ${varName} from "../../../content/questions/${f}";`;
  })
  .join("\n");

const spreads = files.map((_, i) => `  ...(q${i} as ContentQuestion[]),`).join("\n");

const content = `// AUTO-GENERATED by scripts/sync-question-imports.ts — do not edit manually
import type { ContentQuestion } from "@/lib/content/types";
import { findTopicById } from "@/lib/syllabus/loader";
import type { Question } from "@/lib/types";

${imports}

const ALL_CONTENT: ContentQuestion[] = [
${spreads}
];

export function getAllContentQuestions(): ContentQuestion[] {
  return ALL_CONTENT.filter((q) => q.status === "published");
}

export function getContentQuestionById(id: string): ContentQuestion | undefined {
  return ALL_CONTENT.find((q) => q.id === id);
}

export function getContentQuestionsForTopic(topicId: string): ContentQuestion[] {
  const topic = findTopicById(topicId);
  if (!topic) return [];
  const objectiveIds = new Set(topic.learningObjectives.map((lo) => lo.id));
  return getAllContentQuestions().filter((q) => objectiveIds.has(q.objectiveId));
}

export function toPracticeQuestion(q: ContentQuestion): Question {
  return {
    id: q.id,
    objective_id: q.objectiveId,
    status: "published",
    tier: q.tier,
    difficulty: q.difficulty,
    question_type: q.questionType,
    marks: q.marks,
    exam_style: q.examStyle,
    calculator_allowed: q.calculatorAllowed,
    question_text: q.questionText,
    final_answer: q.finalAnswer,
    solution_steps: q.solutionSteps,
    common_mistakes: "",
    tags: [],
  };
}

export function getPracticeQuestions(topicId?: string | null): Question[] {
  const pool = topicId
    ? getContentQuestionsForTopic(topicId)
    : getAllContentQuestions();
  return pool.map(toPracticeQuestion);
}

export function getQuestionCountByObjective(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const q of getAllContentQuestions()) {
    counts[q.objectiveId] = (counts[q.objectiveId] ?? 0) + 1;
  }
  return counts;
}
`;

writeFileSync(OUT, content);
console.log(`Synced ${files.length} question files → ${OUT}`);
