import type { QSpec } from "./types";

export const ALGEBRA_EXT: QSpec[] = [
  // a-nm-01 (5)
  {
    objectiveId: "a-nm-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "reasoning",
    marks: 1,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Write a x a x a x b x b using indices.",
    finalAnswer: "a^3b^2",
    solutionSteps: "There are three factors of a and two factors of b, so the expression is a^3b^2.",
    hints: [
      "Count how many times each letter appears.",
      "Use powers to show repeated multiplication.",
      "Three a's and two b's gives a^3b^2.",
    ],
  },
  {
    objectiveId: "a-nm-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "If x = 3, work out 2x + 5.",
    finalAnswer: "11",
    solutionSteps: "Substitute x = 3: 2(3) + 5 = 6 + 5 = 11.",
    hints: [
      "Replace x with 3.",
      "Work out 2 x 3 first.",
      "Then add 5 to get 11.",
    ],
  },
  {
    objectiveId: "a-nm-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "A rectangle has length x + 2 and width x - 1. Write an expression for its perimeter.",
    finalAnswer: "4x+2",
    solutionSteps: "Perimeter = 2(length + width) = 2((x + 2) + (x - 1)) = 2(2x + 1) = 4x + 2.",
    hints: [
      "Perimeter of a rectangle is 2(l + w).",
      "Add the two expressions first.",
      "Multiply the bracket by 2.",
    ],
  },
  {
    objectiveId: "a-nm-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 1,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "In the expression 7p - 3, what is the coefficient of p?",
    finalAnswer: "7",
    solutionSteps: "The coefficient is the number multiplying p, which is 7.",
    hints: [
      "The coefficient is the number in front of the variable.",
      "Look at the p term only.",
      "The p term is 7p, so coefficient is 7.",
    ],
  },
  {
    objectiveId: "a-nm-01",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "If m = -2, work out 4m^2 - 3.",
    finalAnswer: "13",
    solutionSteps: "Substitute m = -2: 4(-2)^2 - 3 = 4(4) - 3 = 16 - 3 = 13.",
    hints: [
      "Substitute -2 for m.",
      "Square -2 before multiplying by 4.",
      "Then subtract 3.",
    ],
  },

  // a-nm-02 (5)
  {
    objectiveId: "a-nm-02",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Expand and simplify 3(x + 4).",
    finalAnswer: "3x+12",
    solutionSteps: "Multiply 3 by each term: 3x + 12.",
    hints: [
      "Multiply every term inside the bracket by 3.",
      "3 x x = 3x and 3 x 4 = 12.",
      "Write the result as 3x + 12.",
    ],
  },
  {
    objectiveId: "a-nm-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Simplify 5a + 3b - 2a + b.",
    finalAnswer: "3a+4b",
    solutionSteps: "Collect like terms: 5a - 2a = 3a and 3b + b = 4b, so 3a + 4b.",
    hints: [
      "Group a terms and b terms separately.",
      "5a - 2a gives the a part.",
      "3b + b gives the b part.",
    ],
  },
  {
    objectiveId: "a-nm-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Expand and simplify -2(3x - 5) + x.",
    finalAnswer: "-5x+10",
    solutionSteps: "-2(3x - 5) = -6x + 10, then add x: -6x + 10 + x = -5x + 10.",
    hints: [
      "Multiply -2 by both terms in the bracket.",
      "Be careful with signs: -2 x -5 is +10.",
      "Then combine -6x and +x.",
    ],
  },
  {
    objectiveId: "a-nm-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "If x = 2 and y = -1, work out 4x - 3y.",
    finalAnswer: "11",
    solutionSteps: "Substitute values: 4(2) - 3(-1) = 8 + 3 = 11.",
    hints: [
      "Replace x with 2 and y with -1.",
      "Work out each term separately.",
      "Subtracting a negative becomes addition.",
    ],
  },
  {
    objectiveId: "a-nm-02",
    tier: "Foundation",
    difficulty: "Hard",
    questionType: "word_problem",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "A taxi charges a fixed 2.5 pounds plus 1.2 pounds per mile. Write an expression for the cost of m miles.",
    finalAnswer: "1.2m+2.5",
    solutionSteps: "Variable cost is 1.2m and fixed cost is 2.5, so total cost is 1.2m + 2.5.",
    hints: [
      "Cost has a fixed part and a per-mile part.",
      "Per-mile part is 1.2 multiplied by m.",
      "Add the fixed 2.5.",
    ],
  },

  // a-nm-03 (5)
  {
    objectiveId: "a-nm-03",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Factorise fully 6x + 15.",
    finalAnswer: "3(2x+5)",
    solutionSteps: "Common factor is 3, so 6x + 15 = 3(2x + 5).",
    hints: [
      "Find the highest common factor of 6 and 15.",
      "Both terms are divisible by 3.",
      "Write 3 outside the bracket.",
    ],
  },
  {
    objectiveId: "a-nm-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Factorise x^2 + 9x + 20.",
    finalAnswer: "(x+4)(x+5)",
    solutionSteps: "Find numbers that multiply to 20 and add to 9: 4 and 5, so (x + 4)(x + 5).",
    hints: [
      "Look for two numbers with product 20.",
      "Their sum must be +9.",
      "Use those numbers in two brackets.",
    ],
  },
  {
    objectiveId: "a-nm-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Factorise 2x^2 + 7x + 3.",
    finalAnswer: "(2x+1)(x+3)",
    solutionSteps: "2x^2 + 7x + 3 = 2x^2 + 6x + x + 3 = 2x(x + 3) + 1(x + 3) = (2x + 1)(x + 3).",
    hints: [
      "Try splitting the middle term.",
      "You need two terms that make +7x and multiply to 6x^2.",
      "Factor by grouping.",
    ],
  },
  {
    objectiveId: "a-nm-03",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Factorise x^2 - 16.",
    finalAnswer: "(x-4)(x+4)",
    solutionSteps: "This is a difference of squares: x^2 - 4^2 = (x - 4)(x + 4).",
    hints: [
      "Recognise a^2 - b^2 pattern.",
      "Here a is x and b is 4.",
      "Use (a-b)(a+b).",
    ],
  },
  {
    objectiveId: "a-nm-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 2,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Factorise fully 4x^3 - 12x^2.",
    finalAnswer: "4x^2(x-3)",
    solutionSteps: "Greatest common factor is 4x^2, so 4x^3 - 12x^2 = 4x^2(x - 3).",
    hints: [
      "Find the largest common number and variable power.",
      "Both terms share 4 and x^2.",
      "Factor 4x^2 out.",
    ],
  },

  // a-nm-04 (4)
  {
    objectiveId: "a-nm-04",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Simplify (x^2 - 9)/(x - 3).",
    finalAnswer: "x+3",
    solutionSteps: "x^2 - 9 = (x - 3)(x + 3). Cancel x - 3 to get x + 3.",
    hints: [
      "Factorise the numerator first.",
      "Use difference of squares.",
      "Cancel the common factor.",
    ],
  },
  {
    objectiveId: "a-nm-04",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Simplify 3x/8 + x/4.",
    finalAnswer: "5x/8",
    solutionSteps: "Convert x/4 to 2x/8, then add: 3x/8 + 2x/8 = 5x/8.",
    hints: [
      "Use a common denominator of 8.",
      "Rewrite x/4 as 2x/8.",
      "Add the numerators.",
    ],
  },
  {
    objectiveId: "a-nm-04",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Simplify (2x^2y)/(6xy^2).",
    finalAnswer: "x/(3y)",
    solutionSteps: "2/6 = 1/3, x^2/x = x, y/y^2 = 1/y, so expression simplifies to x/(3y).",
    hints: [
      "Simplify number part and variable parts separately.",
      "Use index laws when dividing powers.",
      "Combine the simplified parts carefully.",
    ],
  },
  {
    objectiveId: "a-nm-04",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 4,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Simplify (x^2 - 4x)/(x^2 - 16).",
    finalAnswer: "x/(x+4)",
    solutionSteps: "Factorise top and bottom: x(x - 4)/((x - 4)(x + 4)). Cancel x - 4 to get x/(x + 4).",
    hints: [
      "Factorise numerator and denominator fully.",
      "Look for a common factor to cancel.",
      "Write the final simplified fraction.",
    ],
  },

  // a-gr-01 (4)
  {
    objectiveId: "a-gr-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "graph",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Find the gradient of the line through (1, 2) and (5, 10).",
    finalAnswer: "2",
    solutionSteps: "Gradient = (10 - 2)/(5 - 1) = 8/4 = 2.",
    hints: [
      "Use change in y over change in x.",
      "Subtract coordinates in the same order.",
      "Simplify the fraction.",
    ],
  },
  {
    objectiveId: "a-gr-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "reasoning",
    marks: 1,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "What is the y-intercept of y = -3x + 7?",
    finalAnswer: "7",
    solutionSteps: "In y = mx + c, c is the y-intercept. Here c = 7.",
    hints: [
      "Compare with y = mx + c.",
      "The constant term is c.",
      "Read c directly from the equation.",
    ],
  },
  {
    objectiveId: "a-gr-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "graph",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "For the line y = 2x - 1, find y when x = 4.",
    finalAnswer: "7",
    solutionSteps: "Substitute x = 4: y = 2(4) - 1 = 8 - 1 = 7.",
    hints: [
      "Replace x with 4.",
      "Multiply before subtracting.",
      "Compute 8 - 1.",
    ],
  },
  {
    objectiveId: "a-gr-01",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "For y = 1/x, work out y when x = -2.",
    finalAnswer: "-0.5",
    solutionSteps: "Substitute x = -2: y = 1/(-2) = -0.5.",
    hints: [
      "Use reciprocal: y is 1 divided by x.",
      "Substitute x = -2.",
      "Convert -1/2 to decimal if needed.",
    ],
  },

  // a-gr-02 (4)
  {
    objectiveId: "a-gr-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Find the equation of the line with gradient 3 and y-intercept -4.",
    finalAnswer: "y=3x-4",
    solutionSteps: "Use y = mx + c with m = 3 and c = -4: y = 3x - 4.",
    hints: [
      "Start with y = mx + c.",
      "Put in m = 3.",
      "Put in c = -4.",
    ],
  },
  {
    objectiveId: "a-gr-02",
    tier: "Foundation",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Find the equation of the line through (2, 5) and (6, 13).",
    finalAnswer: "y=2x+1",
    solutionSteps: "Gradient m = (13 - 5)/(6 - 2) = 2. Using point (2,5): 5 = 2(2) + c, so c = 1. Equation is y = 2x + 1.",
    hints: [
      "Find the gradient from the two points.",
      "Substitute one point to find c.",
      "Write the final equation as y = mx + c.",
    ],
  },
  {
    objectiveId: "a-gr-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Find the equation of the line parallel to y = -0.5x + 3 and passing through (4, 1).",
    finalAnswer: "y=-0.5x+3",
    solutionSteps: "Parallel lines have the same gradient, so m = -0.5. Use (4,1): 1 = -0.5(4) + c = -2 + c, so c = 3. Equation is y = -0.5x + 3.",
    hints: [
      "Parallel lines keep the same gradient.",
      "Use the point to solve for c.",
      "Substitute into y = mx + c.",
    ],
  },
  {
    objectiveId: "a-gr-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Find the equation of the line perpendicular to y = 2x - 1 and passing through (0, 3).",
    finalAnswer: "y=-0.5x+3",
    solutionSteps: "Perpendicular gradient is the negative reciprocal of 2, so m = -1/2. Passing through (0,3) gives c = 3. Equation: y = -0.5x + 3.",
    hints: [
      "Find the negative reciprocal of 2.",
      "Use x = 0 to identify c from the point.",
      "Write the line in y = mx + c form.",
    ],
  },

  // a-gr-03 (4)
  {
    objectiveId: "a-gr-03",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "graph",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "The graph y = x^2 - 9 crosses the x-axis at two points. Find the x-coordinates.",
    finalAnswer: "-3,3",
    solutionSteps: "At x-axis, y = 0, so x^2 - 9 = 0, giving x^2 = 9, so x = -3 or x = 3.",
    hints: [
      "Set y to 0 for x-intercepts.",
      "Solve x^2 = 9.",
      "Remember positive and negative roots.",
    ],
  },
  {
    objectiveId: "a-gr-03",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "For y = x^3 + 1, find y when x = -2.",
    finalAnswer: "-7",
    solutionSteps: "Substitute x = -2: y = (-2)^3 + 1 = -8 + 1 = -7.",
    hints: [
      "Substitute -2 into x^3 + 1.",
      "Cube -2 carefully.",
      "Then add 1.",
    ],
  },
  {
    objectiveId: "a-gr-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Solve 1/x = 4.",
    finalAnswer: "1/4",
    solutionSteps: "Multiply both sides by x: 1 = 4x, so x = 1/4.",
    hints: [
      "Clear the denominator by multiplying by x.",
      "Rearrange the linear equation.",
      "Write as a fraction if needed.",
    ],
  },
  {
    objectiveId: "a-gr-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "graph",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "State the coordinates of the turning point of y = (x - 1)^2 + 2.",
    finalAnswer: "(1,2)",
    solutionSteps: "In y = (x - a)^2 + b, turning point is (a, b). Here it is (1, 2).",
    hints: [
      "Recognise vertex form y = (x-a)^2 + b.",
      "Read a and b directly.",
      "Write the coordinate pair.",
    ],
  },

  // a-ei-01 (5)
  {
    objectiveId: "a-ei-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 3x + 5 = 20.",
    finalAnswer: "5",
    solutionSteps: "3x = 20 - 5 = 15, so x = 15/3 = 5.",
    hints: [
      "Subtract 5 from both sides first.",
      "Then divide both sides by 3.",
      "Simplify to get x.",
    ],
  },
  {
    objectiveId: "a-ei-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 5x - 7 = 2x + 11.",
    finalAnswer: "6",
    solutionSteps: "5x - 2x = 11 + 7, so 3x = 18, so x = 6.",
    hints: [
      "Put x terms on one side and numbers on the other.",
      "Simplify to a one-step equation.",
      "Divide to find x.",
    ],
  },
  {
    objectiveId: "a-ei-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 4(x - 2) = 2x + 6.",
    finalAnswer: "7",
    solutionSteps: "Expand: 4x - 8 = 2x + 6. Then 4x - 2x = 6 + 8, so 2x = 14 and x = 7.",
    hints: [
      "Expand the bracket first.",
      "Collect x terms together.",
      "Finish by dividing by 2.",
    ],
  },
  {
    objectiveId: "a-ei-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve x/3 + 4 = 9.",
    finalAnswer: "15",
    solutionSteps: "x/3 = 9 - 4 = 5, so x = 15.",
    hints: [
      "Subtract 4 from both sides.",
      "You then have x/3 = 5.",
      "Multiply both sides by 3.",
    ],
  },
  {
    objectiveId: "a-ei-01",
    tier: "Foundation",
    difficulty: "Hard",
    questionType: "word_problem",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "A rectangle has perimeter 30 cm and length 8 cm. Find the width.",
    finalAnswer: "7",
    solutionSteps: "Perimeter equation: 2l + 2w = 30. Substitute l = 8: 16 + 2w = 30, so 2w = 14 and w = 7.",
    hints: [
      "Use perimeter formula for a rectangle.",
      "Substitute the known length.",
      "Solve the linear equation for w.",
    ],
  },

  // a-ei-02 (5)
  {
    objectiveId: "a-ei-02",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve x^2 - 7x + 12 = 0.",
    finalAnswer: "3,4",
    solutionSteps: "Factorise: x^2 - 7x + 12 = (x - 3)(x - 4) = 0, so x = 3 or x = 4.",
    hints: [
      "Try factorising the quadratic.",
      "Find two numbers that multiply to 12 and add to -7.",
      "Set each bracket equal to zero.",
    ],
  },
  {
    objectiveId: "a-ei-02",
    tier: "Higher",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve x^2 = 81.",
    finalAnswer: "-9,9",
    solutionSteps: "x = +-sqrt(81) = +-9, so x = -9 or x = 9.",
    hints: [
      "Take square roots of both sides.",
      "Include both positive and negative roots.",
      "Write both solutions.",
    ],
  },
  {
    objectiveId: "a-ei-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 2x^2 - 5x - 3 = 0.",
    finalAnswer: "-1/2,3",
    solutionSteps: "Factorise: 2x^2 - 5x - 3 = (2x + 1)(x - 3) = 0, so x = -1/2 or x = 3.",
    hints: [
      "Look for factors of 2x^2 and -3.",
      "Check the middle term becomes -5x.",
      "Set each factor to zero.",
    ],
  },
  {
    objectiveId: "a-ei-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 4,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Solve x^2 + 4x - 1 = 0. Give your answers to 2 decimal places.",
    finalAnswer: "-4.24,0.24",
    solutionSteps: "Using quadratic formula: x = (-4 +- sqrt(4^2 - 4(1)(-1)))/(2) = (-4 +- sqrt(20))/2 = -2 +- sqrt(5). So x approx -4.24 or 0.24.",
    hints: [
      "Use the quadratic formula with a=1, b=4, c=-1.",
      "Work out the discriminant b^2 - 4ac.",
      "Round both roots to 2 decimal places.",
    ],
  },
  {
    objectiveId: "a-ei-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve x(x - 6) = 16.",
    finalAnswer: "-2,8",
    solutionSteps: "x^2 - 6x = 16, so x^2 - 6x - 16 = 0. Factorise: (x - 8)(x + 2) = 0, so x = 8 or x = -2.",
    hints: [
      "Rearrange to make the equation equal to 0.",
      "Factorise the resulting quadratic.",
      "Solve each linear factor.",
    ],
  },

  // a-ei-03 (4)
  {
    objectiveId: "a-ei-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve simultaneously: x + y = 11 and x - y = 3.",
    finalAnswer: "x=7,y=4",
    solutionSteps: "Add equations: 2x = 14, so x = 7. Substitute into x + y = 11 to get y = 4.",
    hints: [
      "Try adding the equations to eliminate y.",
      "Solve for x first.",
      "Substitute back to find y.",
    ],
  },
  {
    objectiveId: "a-ei-03",
    tier: "Foundation",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve simultaneously: y = 2x + 1 and y = 13 - x.",
    finalAnswer: "x=4,y=9",
    solutionSteps: "Set equal: 2x + 1 = 13 - x. Then 3x = 12, so x = 4. Substitute to get y = 9.",
    hints: [
      "Both expressions are equal to y, so set them equal.",
      "Solve the resulting linear equation.",
      "Substitute x into either equation for y.",
    ],
  },
  {
    objectiveId: "a-ei-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 4,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve simultaneously: 2x + y = 10 and x - y = 2.",
    finalAnswer: "x=4,y=2",
    solutionSteps: "Add equations: 3x = 12, so x = 4. Substitute into x - y = 2 gives 4 - y = 2, so y = 2.",
    hints: [
      "Choose elimination by adding equations.",
      "Find x first from the one-variable equation.",
      "Substitute x back to find y.",
    ],
  },
  {
    objectiveId: "a-ei-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 4,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve simultaneously: x + y = 6 and xy = 8.",
    finalAnswer: "(2,4),(4,2)",
    solutionSteps: "Let y = 6 - x. Then x(6 - x) = 8, so 6x - x^2 = 8, giving x^2 - 6x + 8 = 0. Factorise: (x - 2)(x - 4) = 0. So x = 2 or 4. Corresponding pairs are (2,4) and (4,2).",
    hints: [
      "Substitute y = 6 - x into xy = 8.",
      "Rearrange to a quadratic equation.",
      "Find both ordered pairs, not just one.",
    ],
  },

  // a-ei-04 (4)
  {
    objectiveId: "a-ei-04",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 3x - 5 < 10.",
    finalAnswer: "x<5",
    solutionSteps: "3x < 15, so x < 5.",
    hints: [
      "Add 5 to both sides first.",
      "Then divide by 3.",
      "Keep inequality direction the same since dividing by a positive.",
    ],
  },
  {
    objectiveId: "a-ei-04",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve -2x + 7 >= 1.",
    finalAnswer: "x<=3",
    solutionSteps: "-2x >= -6. Dividing by -2 reverses the sign, so x <= 3.",
    hints: [
      "Move the constant first.",
      "Watch what happens when dividing by a negative number.",
      "Flip the inequality sign at that step.",
    ],
  },
  {
    objectiveId: "a-ei-04",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Find all integer values of x that satisfy 1 <= 2x + 3 < 9.",
    finalAnswer: "-1,0,1,2",
    solutionSteps: "Subtract 3: -2 <= 2x < 6. Divide by 2: -1 <= x < 3. Integers are -1, 0, 1, 2.",
    hints: [
      "Work on all three parts of the inequality together.",
      "Subtract 3, then divide by 2.",
      "List only integer values in the final interval.",
    ],
  },
  {
    objectiveId: "a-ei-04",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Solve 5 - 3x > 14.",
    finalAnswer: "x<-3",
    solutionSteps: "-3x > 9. Divide by -3 and reverse the sign: x < -3.",
    hints: [
      "Subtract 5 from both sides first.",
      "Then divide by -3.",
      "Reverse the inequality when dividing by a negative.",
    ],
  },

  // a-sq-01 (4)
  {
    objectiveId: "a-sq-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "The nth term is 4n - 1. Write the first 5 terms.",
    finalAnswer: "3,7,11,15,19",
    solutionSteps: "Substitute n = 1,2,3,4,5 into 4n - 1 to get 3,7,11,15,19.",
    hints: [
      "Start with n = 1 and increase by 1 each time.",
      "Use the same formula for each term.",
      "Write terms in order.",
    ],
  },
  {
    objectiveId: "a-sq-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 1,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "A sequence is 2, 5, 8, 11, ... Write the term-to-term rule.",
    finalAnswer: "add 3",
    solutionSteps: "Each term increases by 3, so the term-to-term rule is add 3.",
    hints: [
      "Compare consecutive terms.",
      "Find the common difference.",
      "State the rule in words.",
    ],
  },
  {
    objectiveId: "a-sq-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 1,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Continue the sequence: 30, 24, 18, 12, ... Give the next two terms.",
    finalAnswer: "6,0",
    solutionSteps: "The sequence decreases by 6 each time, so next terms are 6 then 0.",
    hints: [
      "Find how much the sequence changes each step.",
      "Apply the same change twice.",
      "Check both new terms match the pattern.",
    ],
  },
  {
    objectiveId: "a-sq-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "An arithmetic sequence starts 7, 10, 13, ... Find the 6th term.",
    finalAnswer: "22",
    solutionSteps: "Common difference is 3. Terms are 7,10,13,16,19,22, so 6th term is 22.",
    hints: [
      "Identify the common difference.",
      "Count terms carefully up to the 6th.",
      "You can also use nth term if preferred.",
    ],
  },

  // a-sq-02 (4)
  {
    objectiveId: "a-sq-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Find the nth term of the sequence 5, 8, 11, 14, ...",
    finalAnswer: "3n+2",
    solutionSteps: "Common difference is 3, so start with 3n. When n=1, 3n=3 but term is 5, so add 2. nth term is 3n + 2.",
    hints: [
      "Find the common difference first.",
      "Use difference as coefficient of n.",
      "Adjust with a constant to match first term.",
    ],
  },
  {
    objectiveId: "a-sq-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Find the nth term of the sequence 2, 6, 12, 20, ...",
    finalAnswer: "n^2+n",
    solutionSteps: "Testing n^2 + n gives 2,6,12,20 for n=1,2,3,4, so nth term is n^2 + n.",
    hints: [
      "This is not linear; check second differences.",
      "Try a quadratic form involving n^2.",
      "Verify the rule with several terms.",
    ],
  },
  {
    objectiveId: "a-sq-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "The nth term is 4n - 3. Find the 20th term.",
    finalAnswer: "77",
    solutionSteps: "Substitute n = 20: 4(20) - 3 = 80 - 3 = 77.",
    hints: [
      "Use n = 20 in the formula.",
      "Multiply first, then subtract.",
      "Check arithmetic carefully.",
    ],
  },
  {
    objectiveId: "a-sq-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "For the sequence with nth term n^2 + 2n, which term has value 48?",
    finalAnswer: "6",
    solutionSteps: "Set n^2 + 2n = 48. Then n^2 + 2n - 48 = 0 = (n + 8)(n - 6). So n = 6 or -8, but term number must be positive, so n = 6.",
    hints: [
      "Create an equation by setting nth term equal to 48.",
      "Solve the quadratic equation.",
      "Only a positive integer can be a term number.",
    ],
  },
];
