import type { QSpec } from "./types";

export const NUMBER_EXT: QSpec[] = [
  // n-sc-01 (5)
  {
    objectiveId: "n-sc-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "comparison",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Put these numbers in ascending order: -2, -1.7, -9/5, -1.68",
    finalAnswer: "-2, -9/5, -1.7, -1.68",
    solutionSteps: "-9/5 = -1.8, so -2 < -1.8 < -1.7 < -1.68.",
    hints: [
      "Convert the fraction to a decimal first.",
      "-9/5 is -1.8.",
      "Then order the negatives from most negative to least negative.",
    ],
  },
  {
    objectiveId: "n-sc-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "comparison",
    marks: 1,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Which is greater: 5/12 or 0.41?",
    finalAnswer: "5/12",
    solutionSteps: "5/12 = 0.4166... which is greater than 0.41.",
    hints: [
      "Convert the fraction to a decimal.",
      "5 divided by 12 is 0.4166... recurring.",
      "Compare 0.4166... with 0.41.",
    ],
  },
  {
    objectiveId: "n-sc-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "comparison",
    marks: 1,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Write <, > or = : -0.27 ___ -1/4",
    finalAnswer: "<",
    solutionSteps: "-1/4 = -0.25. Since -0.27 is more negative, -0.27 < -0.25.",
    hints: [
      "Turn -1/4 into a decimal.",
      "-1/4 = -0.25.",
      "On a number line, -0.27 is to the left of -0.25.",
    ],
  },
  {
    objectiveId: "n-sc-01",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "comparison",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Write these in descending order: 3/5, 0.62, 61%, 0.603",
    finalAnswer: "0.62, 61%, 0.603, 3/5",
    solutionSteps: "3/5 = 0.6 and 61% = 0.61. So 0.62 > 0.61 > 0.603 > 0.6.",
    hints: [
      "Convert everything to decimals.",
      "3/5 = 0.6 and 61% = 0.61.",
      "Descending means largest to smallest.",
    ],
  },
  {
    objectiveId: "n-sc-01",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText:
      "Let A = -0.333..., B = -1/3, C = -0.34. Compare A, B and C from greatest to smallest.",
    finalAnswer: "A = B > C",
    solutionSteps: "-1/3 = -0.333..., so A and B are equal. Both are greater than -0.34.",
    hints: [
      "Rewrite -1/3 as a decimal.",
      "-1/3 is exactly -0.333... recurring.",
      "A and B are equal, and both are less negative than C.",
    ],
  },

  // n-sc-02 (5)
  {
    objectiveId: "n-sc-02",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 1,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Work out (-18) + 7",
    finalAnswer: "-11",
    solutionSteps: "Starting at -18 and moving 7 right gives -11.",
    hints: [
      "Add 7 to -18.",
      "You are moving towards zero.",
      "Count up: -18, -17, ..., -11.",
    ],
  },
  {
    objectiveId: "n-sc-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Work out 4.8 ÷ 0.6 + 1.25 x 4",
    finalAnswer: "13",
    solutionSteps: "4.8 ÷ 0.6 = 8 and 1.25 x 4 = 5. Then 8 + 5 = 13.",
    hints: [
      "Do division and multiplication before addition.",
      "4.8/0.6 = 8 and 1.25 x 4 = 5.",
      "Now add the two results.",
    ],
  },
  {
    objectiveId: "n-sc-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 7/12 - 5/18. Give your answer in simplest form.",
    finalAnswer: "11/36",
    solutionSteps: "Common denominator is 36: 7/12 = 21/36 and 5/18 = 10/36. Difference is 11/36.",
    hints: [
      "Find the LCM of 12 and 18.",
      "Convert both fractions to denominator 36.",
      "Subtract numerators and simplify if needed.",
    ],
  },
  {
    objectiveId: "n-sc-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out (3/4 + 5/6) x 2/5. Give your answer in simplest form.",
    finalAnswer: "19/30",
    solutionSteps: "3/4 + 5/6 = 9/12 + 10/12 = 19/12. Then 19/12 x 2/5 = 38/60 = 19/30.",
    hints: [
      "Add inside the bracket first.",
      "Use denominator 12 for 3/4 and 5/6.",
      "Then multiply by 2/5 and simplify.",
    ],
  },
  {
    objectiveId: "n-sc-02",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "word_problem",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText:
      "At 7 am the temperature is -3C. It rises by 11C by midday, then falls by 7C by evening. What is the evening temperature?",
    finalAnswer: "1C",
    solutionSteps: "-3 + 11 = 8, then 8 - 7 = 1.",
    hints: [
      "Find the midday temperature first.",
      "-3 + 11 = 8.",
      "Now subtract 7.",
    ],
  },

  // n-sc-03 (5)
  {
    objectiveId: "n-sc-03",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 1,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Work out sqrt(289).",
    finalAnswer: "17",
    solutionSteps: "17 x 17 = 289, so sqrt(289) = 17.",
    hints: [
      "Think of a square number close to 289.",
      "15^2 = 225 and 20^2 = 400.",
      "17^2 = 289 exactly.",
    ],
  },
  {
    objectiveId: "n-sc-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 2^4 x 2^5.",
    finalAnswer: "512",
    solutionSteps: "When multiplying powers with the same base, add indices: 2^(4+5) = 2^9 = 512.",
    hints: [
      "Use the index law for same bases.",
      "4 + 5 = 9.",
      "Now evaluate 2^9.",
    ],
  },
  {
    objectiveId: "n-sc-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 3^7 ÷ 3^3.",
    finalAnswer: "81",
    solutionSteps: "When dividing powers with the same base, subtract indices: 3^(7-3) = 3^4 = 81.",
    hints: [
      "Use the division index law.",
      "7 - 3 = 4.",
      "3^4 = 81.",
    ],
  },
  {
    objectiveId: "n-sc-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out (5^3 x 5^2) ÷ 5^4.",
    finalAnswer: "5",
    solutionSteps: "Combine indices in the numerator: 5^(3+2) = 5^5. Then 5^5 ÷ 5^4 = 5^(5-4) = 5.",
    hints: [
      "First combine powers in the numerator.",
      "Then divide powers by subtracting indices.",
      "Anything to power 1 is itself.",
    ],
  },
  {
    objectiveId: "n-sc-03",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "If 2^n = 128, find n.",
    finalAnswer: "7",
    solutionSteps: "128 = 2 x 2 x 2 x 2 x 2 x 2 x 2 = 2^7, so n = 7.",
    hints: [
      "Write 128 as a power of 2.",
      "Keep halving by 2: 128, 64, 32, 16, 8, 4, 2, 1.",
      "Count the number of factors of 2.",
    ],
  },

  // n-sc-04 (4)
  {
    objectiveId: "n-sc-04",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Write 180 as a product of prime factors.",
    finalAnswer: "2^2 x 3^2 x 5",
    solutionSteps: "180 = 18 x 10 = (2 x 3 x 3) x (2 x 5) = 2^2 x 3^2 x 5.",
    hints: [
      "Keep splitting into factor pairs.",
      "Continue until all factors are prime.",
      "Collect repeated primes using powers.",
    ],
  },
  {
    objectiveId: "n-sc-04",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Find the HCF of 72 and 90.",
    finalAnswer: "18",
    solutionSteps: "72 = 2^3 x 3^2 and 90 = 2 x 3^2 x 5. Common primes give HCF = 2 x 3^2 = 18.",
    hints: [
      "Prime factorise both numbers.",
      "Take only common prime factors with smallest powers.",
      "Multiply those common factors.",
    ],
  },
  {
    objectiveId: "n-sc-04",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Find the LCM of 24 and 36.",
    finalAnswer: "72",
    solutionSteps: "24 = 2^3 x 3 and 36 = 2^2 x 3^2. LCM uses highest powers: 2^3 x 3^2 = 72.",
    hints: [
      "Prime factorise each number.",
      "For LCM, choose the highest power of each prime.",
      "Multiply the selected powers.",
    ],
  },
  {
    objectiveId: "n-sc-04",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "word_problem",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText:
      "A bus to Town A leaves every 15 minutes and a bus to Town B leaves every 20 minutes. Both leave at 08:00. When will they next leave together?",
    finalAnswer: "09:00",
    solutionSteps: "Find LCM(15, 20) = 60 minutes. 08:00 + 60 minutes = 09:00.",
    hints: [
      "This is an LCM problem.",
      "List multiples of 15 and 20 or use prime factors.",
      "Add the common interval to 08:00.",
    ],
  },

  // n-fdp-01 (4)
  {
    objectiveId: "n-fdp-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 2/3 + 5/9. Give your answer in simplest form.",
    finalAnswer: "11/9",
    solutionSteps: "2/3 = 6/9, so 6/9 + 5/9 = 11/9.",
    hints: [
      "Use a common denominator of 9.",
      "Convert 2/3 to ninths.",
      "Add numerators and keep denominator 9.",
    ],
  },
  {
    objectiveId: "n-fdp-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 3 1/4 - 1 2/3. Give your answer as a mixed number.",
    finalAnswer: "1 7/12",
    solutionSteps: "3 1/4 = 13/4 and 1 2/3 = 5/3. 13/4 - 5/3 = 39/12 - 20/12 = 19/12 = 1 7/12.",
    hints: [
      "Convert mixed numbers to improper fractions first.",
      "Use denominator 12.",
      "Subtract and convert back to a mixed number.",
    ],
  },
  {
    objectiveId: "n-fdp-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out 7/8 x 12/21. Give your answer in simplest form.",
    finalAnswer: "1/2",
    solutionSteps: "12/21 = 4/7. Then 7/8 x 4/7 = 4/8 = 1/2.",
    hints: [
      "Simplify before multiplying.",
      "12/21 simplifies to 4/7.",
      "Cancel common factors and simplify final answer.",
    ],
  },
  {
    objectiveId: "n-fdp-01",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Work out (5/6) ÷ (10/9). Give your answer in simplest form.",
    finalAnswer: "3/4",
    solutionSteps: "(5/6) ÷ (10/9) = (5/6) x (9/10) = 45/60 = 3/4.",
    hints: [
      "Dividing by a fraction means multiply by its reciprocal.",
      "Use (5/6) x (9/10).",
      "Simplify after multiplying.",
    ],
  },

  // n-fdp-02 (4)
  {
    objectiveId: "n-fdp-02",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "conversion",
    marks: 2,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Write 0.125 as a fraction in its simplest form.",
    finalAnswer: "1/8",
    solutionSteps: "0.125 = 125/1000. Divide top and bottom by 125 to get 1/8.",
    hints: [
      "Write the decimal over 1000.",
      "125/1000 can be simplified.",
      "Divide numerator and denominator by 125.",
    ],
  },
  {
    objectiveId: "n-fdp-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "conversion",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Convert 35% to (a) a decimal and (b) a fraction in simplest form.",
    finalAnswer: "0.35 and 7/20",
    solutionSteps: "35% = 35/100 = 0.35. Also 35/100 simplifies to 7/20.",
    hints: [
      "Percent means out of 100.",
      "35% = 35/100.",
      "Write as decimal and simplify the fraction.",
    ],
  },
  {
    objectiveId: "n-fdp-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "conversion",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Convert 3/40 to (a) a decimal and (b) a percentage.",
    finalAnswer: "0.075 and 7.5%",
    solutionSteps: "3/40 = 0.075. Multiply by 100 to get percentage: 7.5%.",
    hints: [
      "Divide 3 by 40 to get the decimal.",
      "To get a percentage, multiply decimal by 100.",
      "Check place value carefully.",
    ],
  },
  {
    objectiveId: "n-fdp-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "conversion",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Express 0.363636... as a fraction in simplest form.",
    finalAnswer: "4/11",
    solutionSteps:
      "Let x = 0.363636... Then 100x = 36.363636... Subtract: 99x = 36, so x = 36/99 = 4/11.",
    hints: [
      "Call the recurring decimal x.",
      "Multiply by 100 to align the repeating block.",
      "Subtract and simplify the resulting fraction.",
    ],
  },

  // n-fdp-03 (4)
  {
    objectiveId: "n-fdp-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "word_problem",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "A jacket costs 150 pounds. It increases in price by 8%. Find the new price.",
    finalAnswer: "162",
    solutionSteps: "8% of 150 is 12. New price = 150 + 12 = 162.",
    hints: [
      "Find 8% of 150 first.",
      "8% = 0.08, so multiply 150 by 0.08.",
      "Add the increase to the original price.",
    ],
  },
  {
    objectiveId: "n-fdp-03",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "word_problem",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "A phone costs 500 pounds. In a sale it is reduced by 12%. Find the sale price.",
    finalAnswer: "440",
    solutionSteps: "12% of 500 is 60. Sale price = 500 - 60 = 440.",
    hints: [
      "Work out the amount reduced first.",
      "12% = 0.12, so reduction is 500 x 0.12.",
      "Subtract the reduction from 500.",
    ],
  },
  {
    objectiveId: "n-fdp-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "After a 25% discount, a bike costs 54 pounds. Work out the original price.",
    finalAnswer: "72",
    solutionSteps: "After 25% off, price is 75% of original. So 0.75 x original = 54, giving original = 54/0.75 = 72.",
    hints: [
      "A 25% discount leaves 75%.",
      "Set up 0.75x = 54.",
      "Divide by 0.75.",
    ],
  },
  {
    objectiveId: "n-fdp-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "A laptop worth 1200 pounds increases in value by 5% in year 1 and by 5% again in year 2. Find its value after 2 years.",
    finalAnswer: "1323",
    solutionSteps: "Multiply by 1.05 twice: 1200 x 1.05 x 1.05 = 1200 x 1.1025 = 1323.",
    hints: [
      "Use a multiplier of 1.05 for each 5% increase.",
      "Two increases means multiply by 1.05^2.",
      "Now multiply by 1200.",
    ],
  },

  // n-ma-01 (4)
  {
    objectiveId: "n-ma-01",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "conversion",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Write 0.000072 in standard form.",
    finalAnswer: "7.2 x 10^-5",
    solutionSteps: "Move the decimal 5 places right to get 7.2, so power is -5: 7.2 x 10^-5.",
    hints: [
      "Standard form is a x 10^n with 1 <= a < 10.",
      "Count how many places the decimal moves.",
      "Small numbers use a negative power.",
    ],
  },
  {
    objectiveId: "n-ma-01",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "conversion",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Write 9.03 x 10^4 as an ordinary number.",
    finalAnswer: "90300",
    solutionSteps: "10^4 means move decimal 4 places right: 9.03 -> 90300.",
    hints: [
      "Positive power means a large number.",
      "Move the decimal right by 4 places.",
      "Fill empty places with zeros.",
    ],
  },
  {
    objectiveId: "n-ma-01",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Work out (6 x 10^3) x (4 x 10^-2). Give your answer in standard form.",
    finalAnswer: "2.4 x 10^2",
    solutionSteps: "6 x 4 = 24 and 10^3 x 10^-2 = 10^1. So result is 24 x 10^1 = 2.4 x 10^2.",
    hints: [
      "Multiply numbers and powers separately.",
      "Add indices for powers of 10.",
      "Adjust so the first number is between 1 and 10.",
    ],
  },
  {
    objectiveId: "n-ma-01",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "calculation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText: "Work out (8.4 x 10^6) ÷ (2 x 10^3). Give your answer in standard form.",
    finalAnswer: "4.2 x 10^3",
    solutionSteps: "8.4/2 = 4.2 and 10^6 ÷ 10^3 = 10^(6-3) = 10^3. So answer is 4.2 x 10^3.",
    hints: [
      "Divide the numbers and divide the powers separately.",
      "Subtract indices when dividing powers of 10.",
      "Check the result is in standard form.",
    ],
  },

  // n-ma-02 (4)
  {
    objectiveId: "n-ma-02",
    tier: "Foundation",
    difficulty: "Easy",
    questionType: "calculation",
    marks: 1,
    examStyle: false,
    calculatorAllowed: false,
    questionText: "Round 47.386 to 1 decimal place.",
    finalAnswer: "47.4",
    solutionSteps: "The second decimal digit is 8, so round the first decimal up: 47.4.",
    hints: [
      "1 decimal place means keep tenths.",
      "Look at the hundredths digit.",
      "8 means round up.",
    ],
  },
  {
    objectiveId: "n-ma-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "calculation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Round 0.009964 to 2 significant figures.",
    finalAnswer: "0.010",
    solutionSteps: "First two significant digits are 9 and 9. Next digit is 6, so 99 rounds to 100, giving 0.010.",
    hints: [
      "Ignore leading zeros when counting significant figures.",
      "The first two significant digits are 9 and 9.",
      "Round up and keep place value.",
    ],
  },
  {
    objectiveId: "n-ma-02",
    tier: "Foundation",
    difficulty: "Medium",
    questionType: "estimation",
    marks: 2,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Estimate (198 x 0.49) ÷ 9.8.",
    finalAnswer: "10",
    solutionSteps: "Round to 1 sf: 198 -> 200, 0.49 -> 0.5, 9.8 -> 10. Then (200 x 0.5)/10 = 100/10 = 10.",
    hints: [
      "Round each number to 1 significant figure.",
      "Compute 200 x 0.5 first.",
      "Then divide by 10.",
    ],
  },
  {
    objectiveId: "n-ma-02",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "estimation",
    marks: 3,
    examStyle: true,
    calculatorAllowed: false,
    questionText: "Estimate (7.98^2) ÷ 0.201.",
    finalAnswer: "320",
    solutionSteps: "Round to 1 sf: 7.98 -> 8 and 0.201 -> 0.2. So estimate is 8^2/0.2 = 64/0.2 = 320.",
    hints: [
      "Round to convenient values first.",
      "Use 8^2 for the numerator.",
      "Dividing by 0.2 is the same as multiplying by 5.",
    ],
  },

  // n-ma-03 (4)
  {
    objectiveId: "n-ma-03",
    tier: "Higher",
    difficulty: "Medium",
    questionType: "reasoning",
    marks: 2,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "A length L is 12.4 cm correct to the nearest 0.1 cm. Write the error interval for L.",
    finalAnswer: "12.35 <= L < 12.45",
    solutionSteps: "Nearest 0.1 means half-step is 0.05. So lower bound is 12.35 and upper bound is 12.45.",
    hints: [
      "Use half the rounding unit.",
      "0.1/2 = 0.05.",
      "Subtract and add 0.05 to 12.4.",
    ],
  },
  {
    objectiveId: "n-ma-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 3,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "a = 7.2 and b = 3.8, both correct to the nearest 0.1. Find the upper bound of a + b.",
    finalAnswer: "11.10",
    solutionSteps: "Upper bound of a is 7.25 and of b is 3.85. Upper bound of a + b is 7.25 + 3.85 = 11.10.",
    hints: [
      "For an upper bound of a sum, use upper bound of each value.",
      "Nearest 0.1 gives +0.05 for each upper bound.",
      "Add the two upper bounds.",
    ],
  },
  {
    objectiveId: "n-ma-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "multi_step",
    marks: 4,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "A rectangle has width 5 cm and length 9 cm, each correct to the nearest cm. Find the lower bound of its area.",
    finalAnswer: "38.25",
    solutionSteps: "Lower bounds are 4.5 cm and 8.5 cm. Lower bound area = 4.5 x 8.5 = 38.25 cm^2.",
    hints: [
      "Use lower bounds for both dimensions.",
      "Nearest cm means subtract 0.5 from each measurement.",
      "Multiply the lower bounds.",
    ],
  },
  {
    objectiveId: "n-ma-03",
    tier: "Higher",
    difficulty: "Hard",
    questionType: "word_problem",
    marks: 4,
    examStyle: true,
    calculatorAllowed: true,
    questionText:
      "Distance is 60 km correct to the nearest km and time is 1.2 h correct to the nearest 0.1 h. Find the upper bound for speed.",
    finalAnswer: "52.61 km/h",
    solutionSteps:
      "Upper bound distance = 60.5 km. Lower bound time = 1.15 h. Upper bound speed = 60.5/1.15 = 52.608... so 52.61 km/h.",
    hints: [
      "For maximum speed use largest distance and smallest time.",
      "Nearest km gives +0.5 and nearest 0.1 h gives -0.05.",
      "Divide 60.5 by 1.15 and round appropriately.",
    ],
  },
];
